2021.4.2 merge 2 develop
openvinotoolkit/model_server pull request #1031
Opened 2021-11-18 15:03 UTC by dtrawins

2021-11-18 15:26 UTC, dkalinowski commented on src/custom_nodes/model_zoo_intel_object_detection/model_zoo_intel_object_detection.cpp
> +
This is not resolved correctly. There is separate task to do it correctly: https://jira.devtools.intel.com/browse/CVS-69864
If we merge this code we will have memory leak or double free issue.

On main, the model zoo custom node does not use internal manager, therefore it does not use preallocated buffers. On develop, it uses preallocated buffers but you do not use it for info[3]. What's more, there will be segfault due to writing to unallocated memory (setting `*outputsCount = 3;` but writting to 4th element).

2021-12-10 11:01 UTC, dkalinowski requested changes
Please compare this:

main:
https://github.com/openvinotoolkit/model_server/tree/main/example_client/cpp#start-the-client-1

develop:
https://github.com/openvinotoolkit/model_server/tree/develop/example_client/cpp#start-the-client-1

The --batch_size parameters differ. 1 on main 4 on develop. 1 is correct.
This change is missing in this PR. Are there maybe more doc changes skipped by mistake during conflict resolving?

2021-12-13 18:34 UTC, rasapala approved these changes
LGTM

2021-12-14 16:31 UTC, dkalinowski approved these changes

2021-12-23 08:18 UTC, dkalinowski approved these changes

2021-12-23 08:38 UTC, merged