Allow negative one for dynamic multiply
openvinotoolkit/model_server pull request #1115
Opened 2022-01-27 09:05 UTC by michalkulakowski

2022-01-27 09:14 UTC, atobiszei commented on src/pipelinedefinition.cpp
>              // TODO -1 vs 0 as demultiplexing value
To remove

2022-01-27 09:15 UTC, atobiszei commented on src/test/schema_test.cpp
> -TEST(SchemaTest, DemultiplexerConfigDemultiplyCountNegativeNotAllowed) {
Do we have positive test for 0 as well?

2022-01-27 13:42 UTC, dkalinowski requested changes
There would be 90% less amount of changes required if we kept using 0 as dynamic demultiplyCount and only converted -1 to 0 at config reading time. This would also only require 1 more functional test that given config with -1 to works as well.

2022-01-27 13:43 UTC, dkalinowski commented
There was also suggestion that we accepted `auto` keyword as well. Do we want to support it? @atobiszei @dtrawins

2022-01-27 15:23 UTC, dkalinowski approved these changes

2022-01-28 08:58 UTC, atobiszei approved these changes

2022-01-28 10:14 UTC, merged