model_cache docs fix
openvinotoolkit/model_server pull request #1144
Opened 2022-02-10 12:46 UTC by ficol

2022-02-10 12:51 UTC, dkalinowski approved these changes

2022-02-10 12:52 UTC, dkalinowski requested changes
Isn't it used in more places? Everywhere we use GPU device in example. For example here: https://github.com/openvinotoolkit/model_server/blob/develop/docs/docker_container.md#running-openvino-model-server-with-ai-accelerators-ncs-hddl-and-gpu-

Please find remaining usages

2022-02-16 08:40 UTC, dkalinowski approved these changes

2022-02-16 12:24 UTC, atobiszei approved these changes

2022-02-16 12:26 UTC, merged