Auto plugin docs.
openvinotoolkit/model_server pull request #1213
Opened 2022-03-22 12:11 UTC by rasapala

2022-03-22 14:15 UTC, dtrawins requested changes

2022-03-22 14:15 UTC, dtrawins commented on docs/accelerators.md
> +> NOTE: --target_device AUTO and --shape 'auto' should not be used together.
```suggestion
> NOTE: currently, AUTO plugin cannot be used with `--shape auto` parameter while GPU device is enabled. 
```

2022-03-22 14:15 UTC, dtrawins commented on docs/accelerators.md
> +        docker run --rm -d -v <model_path>:/opt/model -p 9001:9001 openvino/model_server:latest \
such command will work only with CPU device. While other device is the be enabled, also it's special docker parameters needs to be added also.
For example with GPU also --device /dev/dri and group context etc.
It should be mentioned are even added to the example

2022-03-22 14:15 UTC, dtrawins commented on docs/accelerators.md
> +To enable AUTO Plugin as target device, use the following command:
It should be mentioned how to tune the performance with AUTO plugin - PERFORMANCE_HINT LATENCY or THROUGHPUT. What is the default?

2022-03-23 09:21 UTC, dtrawins commented on docs/accelerators.md
> +To enable AUTO Plugin as target device, use the following command:
```suggestion
Below is an example of the command with AUTO Plugin as target device. It includes extra docker parameters to enable GPU (/dev/dri) , beside CPU.
```

2022-03-23 09:21 UTC, dtrawins commented on docs/accelerators.md
> +## Performance Hints
It duplicates the content from performance_tuning doc

2022-03-23 11:30 UTC, dtrawins approved these changes

2022-03-23 11:39 UTC, dkalinowski approved these changes

2022-03-23 11:42 UTC, merged