Add warn log for unsupported keys in plugin config
openvinotoolkit/model_server pull request #1254
Opened 2022-04-14 15:03 UTC by michalkulakowski

2022-04-14 15:21 UTC, atobiszei commented
> _ No description provided. _

Please add issue id.

2022-04-14 15:24 UTC, atobiszei commented on src/modelmanager.cpp
> +            SPDLOG_LOGGER_WARN(modelmanager_logger, "Plugin config key: {} not found in supported config keys for available devices", config.first);
Should we just stop at logging warning?
User specified that model should load with specified plugin configuration. Model cannot load with that configuration so we skip it and just print warning?

Either way I am not sure if we shouldn't put similar logic inside model Instance?

2022-04-19 08:06 UTC, dkalinowski commented on src/plugin_configuration.cpp
> +Status validatePluginConfiguration(const plugin_config_t& pluginConfig, const std::string& targetDevice, const ov::Core& ieCore) {
Isnt this related to openvino utils? We may place it in ov_utils.hpp. What do you think?

2022-04-19 08:19 UTC, dkalinowski commented on src/modelinstance.cpp
> +    auto status = validatePluginConfiguration(config.getPluginConfig(), config.getTargetDevice(), ieCore);
Why do we validate configuration twice? Once after config parse and here after model compilation?

2022-04-28 10:14 UTC, atobiszei approved these changes

2022-04-29 09:19 UTC, dkalinowski requested changes
Could we add unit test checking if passing CPU_THROUGHPUT_STREAMS works but WRONG_KEY does not?

2022-04-29 11:43 UTC, dkalinowski approved these changes

2022-04-29 12:26 UTC, merged