Fixed invalid docker tag
openvinotoolkit/model_server pull request #1288
Opened 2022-06-02 16:13 UTC by bstrzele

2022-06-02 19:28 UTC, michalkulakowski approved these changes

2022-06-03 11:20 UTC, rasapala approved these changes
LGTM

2022-06-06 08:52 UTC, dtrawins requested changes
@bstrzele it should be corrected also in demos/optical_character_recognition/python/README.md

2022-06-08 10:46 UTC, dtrawins approved these changes

2022-06-08 10:47 UTC, merged