Reduce size of stream analysis docker image
openvinotoolkit/model_server pull request #1459
Opened 2022-10-06 14:53 UTC by bstrzele

2022-10-07 07:45 UTC, dkalinowski commented on demos/real_time_stream_analysis/python/install_opencv.sh
> +#!/bin/bash
This new file duplicates model_server/third_party/opencv/install_opencv.sh

2022-10-07 08:24 UTC, dtrawins requested changes

2022-10-07 08:24 UTC, dtrawins commented on demos/real_time_stream_analysis/python/Dockerfile
>  RUN pip3 install -r /real_time_stream_analysis/requirements.txt
add --no-cache-dir

2022-10-07 08:24 UTC, dtrawins commented on demos/real_time_stream_analysis/python/Dockerfile
> +RUN apt -y update && apt install -y --no-install-recommends libgl1 libglib2.0-0 python3-pip
use apt-get instead of apt
add  && rm -rf /var/lib/apt/lists/*

2022-10-14 08:51 UTC, atobiszei approved these changes

2022-10-25 08:02 UTC, dkalinowski approved these changes

2022-10-25 09:02 UTC, mzegla commented
What's the final size of the image?

2022-10-26 06:08 UTC, bstrzele commented
Final size: 526MB

2022-10-26 08:48 UTC, mzegla approved these changes
Let's separately explore minimal installation possibility to see if we can shrink the image even more.

2022-11-02 08:39 UTC, dtrawins approved these changes

2022-11-02 08:39 UTC, merged