Fix performance tuning
openvinotoolkit/model_server pull request #1584
Opened 2022-12-09 07:14 UTC by michalkulakowski

2022-12-13 12:36 UTC, dtrawins requested changes
There are more out of data info in this page. For example old parameters which are deprecated now.

2022-12-19 22:16 UTC, dtrawins reviewed
It would be good to include a recommendation to use REST with KServe raw input

2022-12-19 22:16 UTC, dtrawins commented on docs/performance_tuning.md
> +| INFERENCE_NUM_THREADS       | Specifies the number of threads that CPU plugin should use for inference.     |
there is no param INFERENCE_NUM_THREADS

2022-12-20 09:04 UTC, rasapala approved these changes
LGTM

2022-12-20 22:22 UTC, dtrawins approved these changes

2022-12-21 11:04 UTC, merged