Fixed mediapipe does not return an error when it has the same name as model or DAG
openvinotoolkit/model_server pull request #2060
Opened 2023-09-22 07:15 UTC by bstrzele

2023-09-22 10:12 UTC, rasapala approved these changes
1 minor fix.

2023-09-22 10:12 UTC, rasapala commented on src/mediapipe_internal/mediapipegraphdefinition.cpp
> +        SPDLOG_LOGGER_ERROR(modelmanager_logger, "Mediapipe graph: {} is already occupied by model or pipeline.", this->getName());
```suggestion
        SPDLOG_LOGGER_ERROR(modelmanager_logger, "Mediapipe graph name: {} is already occupied by model or pipeline.", this->getName());
```

2023-09-22 10:19 UTC, atobiszei requested changes
I think this is insufficient fix in few aspects. We only eliminate problem that we can't now load MP when there is already model loaded with the same name.

1) What happens when we have DAG with the same name?
2) What happens if we try to load model when there is already MP loaded with the same name?
3) What happens if we try to load DAG when there is already MP loaded with the same name?

There is also no test to confirm that this fix is working.

2023-09-22 10:19 UTC, atobiszei commented on src/mediapipe_internal/mediapipegraphdefinition.cpp
> +        return StatusCode::MEDIAPIPE_GRAPH_INITIALIZATION_ERROR;
Have separate status code for this error as we won';t be able to differentiate between MP error during graph.Initialize(), and this configuration issue.

2023-09-25 07:28 UTC, atobiszei commented on src/mediapipe_internal/mediapipegraphdefinition.cpp
> +    if (std::find_if(models.begin(), models.end(), [this](auto pair) { return this->getName() == pair.first; }) != models.end() || manager.pipelineDefinitionExists(this->getName())) {
```suggestion
    if (manager.modelExists(this->getName()) || manager.pipelineDefinitionExists(this->getName())) {
```

2023-09-25 07:29 UTC, atobiszei commented on src/mediapipe_internal/mediapipegraphdefinition.cpp
> +    if (std::find_if(models.begin(), models.end(), [this](auto pair) { return this->getName() == pair.first; }) != models.end() || manager.pipelineDefinitionExists(this->getName())) {
This way we leave thread safety as the responsibility of modelmanager. In fact we shouldn't expose getModels as public

2023-09-25 10:28 UTC, atobiszei approved these changes

2023-09-25 11:19 UTC, merged