Updated stream client
openvinotoolkit/model_server pull request #2170
Opened 2023-11-27 08:07 UTC by bstrzele

2023-12-14 10:04 UTC, rasapala approved these changes
LGTM

2023-12-22 15:47 UTC, dtrawins approved these changes

2023-12-26 22:54 UTC, dtrawins requested changes
Doesn't work with --output_stream screen

2024-01-09 13:09 UTC, dtrawins commented on demos/common/stream_client/Dockerfile
>  ENTRYPOINT ["python3", "/workspace/rtsp_client.py"]
entrypoint should be updated to client.py

2024-01-09 15:52 UTC, dtrawins approved these changes

2024-01-10 14:43 UTC, merged