Update build_from_source
openvinotoolkit/model_server pull request #2272
Opened 2024-01-17 21:00 UTC by michalkulakowski

2024-01-18 15:12 UTC, dtrawins requested changes

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +To build image with support of additional plugins use parameters described in paragraphs below.
```suggestion
To build the image with non default configuration, add parameters described below.
```

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +make release_image PYTHON_DISABLE=0
```suggestion
make release_image PYTHON_DISABLE=1
```

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +When set to `1`, OpenVINO&trade Model Server will be built with [GPU plugin](https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_supported_plugins_GPU.html) support. Default value: `0`.
```suggestion
When set to `1`, OpenVINO&trade Model Server will be built with the drivers required by [GPU plugin](https://docs.openvino.ai/2023.2/openvino_docs_OV_UG_supported_plugins_GPU.html) support. Default value: `0`.
```

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +Building minimalistic OVMS docker image requires disabling all additional features:
```suggestion
Building minimalistic OVMS docker image requires disabling all optional features:
```

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +Building ovms.tar.gz package is possible by using targz_package target:
```suggestion
The binary packages includes the `ovms` executable and linked libraries for bare metal deployments. It includes also a shared library for the model server CAPI interface. Building `ovms.tar.gz` package is possible by using `targz_package` target:
```

2024-01-18 15:12 UTC, dtrawins commented on docs/build_from_source.md
> +make targz_package
```suggestion
make targz_package PYTHON_DISABLE=1
```

2024-01-19 09:22 UTC, mzegla reviewed
I wonder if we should add removed contents to developer guide maybe?
Describing `docker_build` target and it's artifacts seems valuable to me

2024-01-19 09:22 UTC, mzegla commented on docs/build_from_source.md
> +
Maybe add note that Python is enabled via MediaPipe and configuration with `MEDIAPIPE_DISABLE=1 PYTHON_DISABLE=0` is invalid

2024-01-19 09:22 UTC, mzegla commented on docs/build_from_source.md
> +When set to `0`, OpenVINO&trade Model Server will be built with [Python Nodes](python_support/quickstart.md) support. Default value: `0`.
Can we say what happens when set to `1`? It feels more natural imho,  since it's basically a flag. 
We could do the same for `MEDIAPIPE_DISABLE`

2024-01-22 08:26 UTC, dtrawins approved these changes

2024-01-22 11:01 UTC, mzegla approved these changes

2024-01-22 13:04 UTC, merged