Added string precision metadata
openvinotoolkit/model_server pull request #2332
Opened 2024-02-20 11:27 UTC by bstrzele

2024-02-22 11:24 UTC, dkalinowski commented on src/capi_frontend/capi.cpp
> +    if (status.ok()) {
Is it good place for validation? We already have validate step, check `RequestValidator<ovms::InferenceRequest, InferenceTensor, const InferenceTensor*, signed_shape_t>::validatePrecision`

2024-02-26 12:34 UTC, dkalinowski commented on src/serialization.cpp
> +        responseOutput.mutable_contents()->add_bytes_contents((char*)tensor.data(), tensor.get_byte_size());
@bstrzele  Why are you performing string serialization in this PR? It is out of scope in this release. What does tensor.data() return when the type is string?

2024-02-26 12:35 UTC, dkalinowski requested changes
Unit tests are missing

2024-02-28 14:28 UTC, dkalinowski commented on src/predict_request_validation_utils.cpp
> +        return Status(StatusCode::INVALID_PRECISION, "Inference on models using string precision input with capi is unsupported");
Unit test needed

2024-03-04 09:16 UTC, atobiszei commented
Merged already

2024-03-04 09:16 UTC, closed without merging

2024-03-04 09:17 UTC, dkalinowski commented
https://github.com/openvinotoolkit/model_server/pull/2341