print_summary option to benchmark_client to parse benchmark results.
openvinotoolkit/model_server pull request #2397
Opened 2024-04-05 20:41 UTC by psakamoori

Added print_summary command arg to benchmark_client app to summarize benchmark results as shown below 

```
docker run --network host benchmark_client -a localhost -r 8000 -m face-detection-retail-0005 -p 9000 -s 2 3 300 300 -t 20 -u 2 -w 10  -ps
Client 2.7
NO_PROXY=localhost no_proxy=localhost python3 /ovms_benchmark_client/main.py -a localhost -r 8000 -m face-detection-retail-0005 -p 9000 -s 2 3 300 300 -t 20 -u 2 -w 10 -ps
          XI worker: start workload...

### Benchmark Parameters ###
 Model: face-detection-retail-0005
 Input shape: ['2', '3', '300', '300']
 Request concurrency: 1
 Test Duration (s): Total (t) : 20.00 | Warmup (u): 2.00 | Window (w): 10.00

### Benchmark Summary ###
 ## General Metrics ##
 Duration(s): Total: 20.01 | Window: 10.01
 Batches: Total: 1781 | Window: 891

 ## Latency Metrics (ms) ##
 Mean: 11.20 | stdev: 0.74 | p50: 12.78 | p90: 15.26 | p95: 15.56

 ## Throughput Metrics (fps) ##
 Frame Rate (FPS): Brutto : 89.01 | Netto: 89.24 
 Batch Rate (batches/s): Brutto: 89.01 | Netto: 89.24
```

Currently print_all results need manually parsing to understand the over-all performance summary. This PR helps to automate the print_all results parsing and summarize the performance benchmark results.

2024-04-09 06:59 UTC, ravi9 requested changes
Minor changes

2024-04-09 06:59 UTC, ravi9 commented on demos/benchmark/python/main.py
> +            sys.stdout.write(f" Frame Rate (FPS): Brutto : {common_results['brutto_frame_rate']:.2f}")
```suggestion
            sys.stdout.write(f" Frame Rate (FPS): Brutto: {common_results['brutto_frame_rate']:.2f}")
```

2024-04-09 06:59 UTC, ravi9 commented on demos/benchmark/python/main.py
> +            sys.stdout.write(f" Test Duration (s): Total (t) : {total_t:.2f}")
```suggestion
            sys.stdout.write(f" Test Duration (s): Total (t): {total_t:.2f}")
```

2024-04-09 06:59 UTC, ravi9 commented on demos/benchmark/python/main.py
> +                        help="flag to print results summary")
```suggestion
                        help="flag to print output summary")
```

2024-04-09 06:59 UTC, ravi9 commented on demos/benchmark/python/README.md
> + Frame Rate (FPS): Brutto : 89.01 | Netto: 89.24
```suggestion
 Frame Rate (FPS): Brutto: 89.01 | Netto: 89.24
```

2024-04-10 08:14 UTC, dtrawins approved these changes

2024-04-15 09:12 UTC, kpapis commented on demos/benchmark/python/README.md
> +Sample ouptut log with results summary
```suggestion
Sample output log with results summary:
```

2024-04-15 09:13 UTC, kpapis commented on demos/benchmark/python/README.md
> +Summary of the benchmark results can be viewed with command option ```-ps```
```suggestion
Summary of the benchmark results can be viewed with command option ```-ps```.
```

2024-04-15 09:14 UTC, kpapis approved these changes

2024-04-24 06:57 UTC, merged