Mkulakow/fix status bug
openvinotoolkit/model_server pull request #2585
Opened 2024-07-26 13:39 UTC by michalkulakowski

### 🛠 Summary

https://jira.devtools.intel.com/browse/CVS-143849

### 🧪 Checklist

- [x] Unit tests added.
- ~[ ] The documentation updated.~
- ~[ ] Change follows security best practices.~
``

2024-08-01 07:22 UTC, rasapala requested changes, later dismissed

2024-08-01 07:22 UTC, rasapala commented on src/mediapipe_internal/mediapipegraphexecutor.hpp
> +        MP_RETURN_ON_FAIL(graph.WaitUntilIdle(), "graph wait until idle", mediapipeAbslToOvmsStatus(status.code()));
Check status instead of another call.

2024-08-14 09:40 UTC, dkalinowski approved these changes

2024-08-14 09:45 UTC, atobiszei approved these changes
Please add description in final commit what is the reason behind this change (why this specific code needs mapping) -
related to:
https://github.com/openvinotoolkit/mediapipe/pull/80/files

2024-08-19 06:36 UTC, merged