node
openvinotoolkit/model_server pull request #2627
Opened 2024-08-16 12:59 UTC by bstrzele

### 🛠 Summary

JIRA/Issue if applicable.
Describe the changes.

### 🧪 Checklist

- [ ] Unit tests added.
- [ ] The documentation updated.
- [ ] Change follows security best practices.
``

2024-08-19 22:04 UTC, dtrawins requested changes

2024-08-19 22:04 UTC, dtrawins commented on src/test/llmnode_test.cpp
> +class EmbeddingsFlowHttpTest : public ::testing::Test {
/src/test/mediapipeflow_test.cpp should be extended to test the presence of new calculator

2024-08-20 09:51 UTC, dtrawins commented on src/test/embeddings/graph.pbtxt
> +    output_stream: "LOOPBACK:loopback"
loopback is not needed

2024-08-21 11:42 UTC, dtrawins approved these changes

2024-08-21 12:23 UTC, michalkulakowski approved these changes

2024-08-23 06:59 UTC, mzegla approved these changes

2024-08-23 07:55 UTC, merged