CVS-154700, Implement LoadLibrary for windows with GetProcAddress
openvinotoolkit/model_server pull request #2874
Opened 2024-11-25 08:23 UTC by 18582088138

### 🛠 Summary

Implement LoadLibrary for windows with GetProcAddress - dlopen.
JIRA/Issue : [CVS-154700](https://jira.devtools.intel.com/browse/CVS-154700)

### 🧪 Checklist

- [ ] Unit tests added.
- [ ] The documentation updated.
- [ ] Change follows security best practices.
``

2024-12-10 10:47 UTC, rasapala requested changes
Enable skipped tests: NodeLibraryManagerTest

2025-01-03 13:45 UTC, rasapala approved these changes

2025-01-03 13:58 UTC, bstrzele commented on src/test/test_utils.cpp
> +        // Change paths to linux separator for JSON parser compatyility in configs
```suggestion
        // Change paths to linux separator for JSON parser compatibility in configs
```

2025-01-03 13:59 UTC, bstrzele approved these changes

2025-01-07 01:59 UTC, merged