Add test showing bug in model reload with (in|out)puts info
openvinotoolkit/model_server pull request #321
Opened 2020-10-26 09:38 UTC by atobiszei

2020-10-26 09:45 UTC, atobiszei commented
Output of undisabled test:
`[2020-10-26 09:32:40.534] [info] STATUS CHANGE: Version 0 of model dummy status change. New status: ( "state": "AVAILABLE", "error_code": "OK" )
src/test/modelinstance_test.cpp:248: Failure
Expected equality of these values:
  1
  inputsMap.size()
    Which is: 2
src/test/modelinstance_test.cpp:249: Failure
Expected equality of these values:
  1
  outputsMap.size()
    Which is: 2
b
input
a
output
[  FAILED  ] TestReloadModel.SuccessfulReloadFromAlreadyLoadedWithChangedModelMapping (59 ms)`

2020-10-26 09:50 UTC, dkalinowski requested changes

2020-10-26 09:50 UTC, dkalinowski commented on src/test/modelinstance_test.cpp
> +    std::string dummy_model = dir.u8string() + "/src/test/dummy";
Unused temp variable

2020-10-26 10:45 UTC, dkalinowski approved these changes

2020-10-30 11:40 UTC, rasapala approved these changes
LGTM

2020-12-17 14:42 UTC, atobiszei commented
Closing since fix for that case is already merged together with this commit.

2020-12-17 14:42 UTC, closed without merging