Cvs 35968 better handling of anonymous shape param
openvinotoolkit/model_server pull request #339
Opened 2020-11-09 08:25 UTC by michalkulakowski

2020-11-09 09:22 UTC, rasapala requested changes

2020-11-09 09:22 UTC, rasapala commented on src/modelconfig.cpp
> +                        SPDLOG_WARN("Provided one of provided shapes name: {} is forbidden and will be omitted", ANONYMOUS_INPUT_NAME);
Provided shape name: {} is forbidden

2020-11-10 08:40 UTC, rasapala approved these changes
LGTM

2020-11-10 14:16 UTC, dkalinowski requested changes
Please also create task for long term solution - without forbidding any input name.

2020-11-10 14:16 UTC, dkalinowski commented on src/test/modelconfig_test.cpp
> +                    "shape": {"ANONYMOUS_INPUT_NAME": "(1, 3, 600, 600)"}
Can we somehow avoid hardcoding ANONYMOUS_INPUT_NAME? We already have it defined somewhere else under alias `ANONYMOUS_INPUT_NAME`. Maybe we could somehow use it here?

2020-11-10 15:22 UTC, dkalinowski approved these changes

2020-11-11 16:40 UTC, merged