CVS-41787 Add pipeline Metadata stress tests (#407)
openvinotoolkit/model_server pull request #427
Opened 2020-12-17 14:39 UTC by atobiszei

* Revert "Revert "Stress tests for DAG runtime modifications (#382)" (#413)"

This reverts commit c7ce3296ff8fa9206d9144b4f15e751181be96f0.

* Fix bug that reloading state was not considered in waitForLoaded

JIRA:CVS-45093

* Add pipeline Metadata stress tests

TODO:
-> getModelStatus

JIRA:CVS-41787

2020-12-21 11:56 UTC, dkalinowski approved these changes

2020-12-21 15:09 UTC, rasapala requested changes

2020-12-21 15:09 UTC, rasapala commented on src/pipelinedefinition.cpp
> +                       !this->status.canEndLoaded();
Can you make this function name more descriptive ?

2020-12-22 16:01 UTC, rasapala approved these changes
LGTM

2020-12-22 17:08 UTC, merged