Add mention about binary inputs to the docs
openvinotoolkit/model_server pull request #620
Opened 2021-04-16 06:06 UTC by michalkulakowski

2021-04-16 12:27 UTC, dkalinowski approved these changes

2021-04-16 13:05 UTC, rasapala approved these changes
LGTM

2021-04-16 14:38 UTC, dtrawins requested changes

2021-04-16 14:38 UTC, dtrawins commented on docs/model_server_rest_api.md
> +Sends requests via TensorFlow Serving RESTful API using images in base64 encoded string or numpy format. It displays performance statistics and optionally the model accuracy.
I would put it as numpy array or binary format.
base64 is just encoding to json but originally the input data is an array or binary image.

2021-04-16 14:38 UTC, dtrawins commented on docs/model_server_rest_api.md
> +Read [How to specify input tensors in row format](https://www.tensorflow.org/tfx/serving/api_rest#specifying_input_tensors_in_row_format) and [How to specify input tensors in column format](https://w
Check [How to encode binary values](https://www.tensorflow.org/tfx/serving/api_rest#encoding_binary_values)

2021-04-26 15:59 UTC, dtrawins approved these changes

2021-05-06 07:30 UTC, merged