OV Operator 0.2
openvinotoolkit/model_server pull request #684
Opened 2021-06-06 21:18 UTC by dtrawins

2021-06-14 12:58 UTC, mzegla commented on extras/openvino-operator-openshift/tests/README.md
> +export IMG=quay.io/openvino/ovms-operator:0.1.0
Will this still be 0.1.0 ?

2021-06-14 12:58 UTC, mzegla commented on extras/openvino-operator-openshift/tests/README.md
> +cd community-operators/upstream-community-operators/ovms-operator/0.1.0
Will this still be 0.1.0 ?

2021-06-14 12:58 UTC, mzegla commented on extras/openvino-operator-openshift/tests/sample1.yaml
> +  https_proxy: http://proxy-chain.intel.com:911
Should intel proxy information be displayed here?

2021-06-14 12:58 UTC, mzegla commented on extras/openvino-operator-openshift/tests/sample2.yaml
> +  https_proxy: http://proxy-chain.intel.com:911
Should intel proxy information be displayed here?

2021-06-14 12:58 UTC, mzegla commented on extras/ovms-operator/Makefile
> +VERSION ?= 0.0.1
Before I saw version 0.1.0. Does this concern the same thing? If so perhaps we should have the same way of defining version (0.1.0 or 0.0.1). 
btw. shouldn't it be 0.0.2 with the new version?

2021-06-14 12:58 UTC, mzegla commented on extras/ovms-operator/Makefile
> +# This recipe invokes 'opm' in 'semver' bundle add mode. For more information on add modes, see:
semver?

2021-06-22 08:53 UTC, rasapala requested changes
https://github.com/openvinotoolkit/model_server/pull/721/files

2021-06-22 09:20 UTC, rasapala approved these changes
LGTM

2021-06-22 09:36 UTC, mzegla approved these changes

2021-06-22 10:45 UTC, merged