Remove pragma
openvinotoolkit/model_server pull request #882
Opened 2021-08-26 07:08 UTC by michalkulakowski

2021-08-31 07:29 UTC, dkalinowski commented on src/test/stateful_modelinstance_test.cpp
> -#pragma GCC diagnostic push
You have removed push but there is pop still in the file.

2021-08-31 13:55 UTC, dkalinowski commented on src/test/deserialization_tests.cpp
> +    InferenceEngine::InferRequest inferRequest = execNetwork.CreateInferRequest();
Why can't we just use ` InferenceEngine::InferRequest inferRequest;` anymore? Precision check happens before `InputSink::give` so there should be no problem using inferRequest this way. Is the default constructor removed? Are there any other constructors now? Or the only way is using CreateInferRequest?

2021-08-31 13:55 UTC, dkalinowski commented on src/test/deserialization_tests.cpp
>      std::shared_ptr<MockIInferRequestFailingInSetBlob> mInferRequestPtr =
This variable is unused

2021-08-31 13:56 UTC, dkalinowski commented on src/test/deserialization_tests.cpp
>      std::shared_ptr<MockIInferRequestFailingInSetBlob> mInferRequestPtr =
If we do not mock infer requests anymore, we do not need `MockIInferRequestFailingInSetBlob` as well.

2021-09-01 08:43 UTC, atobiszei commented on src/test/deserialization_tests.cpp
> -
There should be pop at the end of the file removed as well

2021-09-01 08:53 UTC, atobiszei requested changes

2021-09-01 08:53 UTC, atobiszei commented on src/test/deserialization_tests.cpp
> +    SPDLOG_ERROR(status.getCode());
leftover debug? FYI you can have in L237 in case of debugging errors.
EXPECT_TRUE(status.ok()) << status.string() << " " << status.getCode();

2021-09-01 08:53 UTC, atobiszei commented on src/test/sequence_manager_test.cpp
> -#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
unremoved pop at the EOL?

2021-09-01 08:53 UTC, atobiszei commented on src/test/sequence_test.cpp
> -#pragma GCC diagnostic push
unremoved pop at the EOL?

2021-09-01 08:53 UTC, atobiszei commented on src/test/serialization_tests.cpp
> -#pragma GCC diagnostic push
unremoved pop at the EOL?

2021-09-01 08:53 UTC, atobiszei commented on src/test/stateful_config_test.cpp
> -#pragma GCC diagnostic push
unremoved pop at the EOL?

2021-09-01 08:53 UTC, atobiszei commented on src/test/stateful_test_utils.hpp
> -#pragma GCC diagnostic push
unremoved pop at the EOL?

2021-09-01 11:12 UTC, dkalinowski approved these changes

2021-09-02 09:32 UTC, dkalinowski requested changes
Please also remove `MockIInferRequestProperGetBlob` since this also inherits from `MockIInferRequest` and is unused.
We can also get rid of `mock_iinferrequest.hpp` since it is also not used anymore.

2021-09-02 09:43 UTC, dkalinowski approved these changes

2021-09-02 09:57 UTC, atobiszei commented on src/test/deserialization_tests.cpp
> +    inferRequest.SetBlob("b", mockBlobPtr);
```suggestion
    inferRequest.SetBlob(DUMMY_MODEL_INPUT_NAME, mockBlobPtr);
```

2021-09-02 09:57 UTC, atobiszei commented on src/test/deserialization_tests.cpp
> +        std::string("b"),
```suggestion
        DUMMY_MODEL_INPUT_NAME,
```

2021-09-02 09:59 UTC, atobiszei approved these changes

2021-09-02 12:40 UTC, merged