Fixes in documentation
openvinotoolkit/model_server pull request #920
Opened 2021-09-09 13:11 UTC by atobiszei

Change TF version in Ensemble example since 1.15 is no longer
available in pip3.

2021-09-10 09:33 UTC, rasapala requested changes

2021-09-13 07:27 UTC, atobiszei commented on docs/developer_guide.md
> +3.	Assuming resnet50 model is repared for OVMS in /models catalog recompile the OpenVINO Model Server with debug symbols using command:
```suggestion
3.	Assuming resnet50 model is prepared for OVMS in /models catalog recompile the OpenVINO Model Server with debug symbols using command:
```

2021-09-13 07:48 UTC, rasapala approved these changes
LGTM

2021-09-13 08:05 UTC, dkalinowski commented on docs/ensemble_scheduler.md
> +~$ pip3 install tensorflow==2.3.1
Have you tested the script manually? As far I remember `argmax_sum.py` requires tensorflow 1.15.

2021-09-13 09:15 UTC, dkalinowski approved these changes

2021-09-13 09:34 UTC, merged